### ISSUE TITLE
Dark Version

### ISSUE THREAD

**Issue by oxhey** [itsamoreh/reddit-no-frills#1]
A dark version would be nice, or a switch so the user can flip between light and dark.

**Comment by itsamoreh** [comment]
Thanks for the comment! I'll add a dark version in the next few weeks.

EDIT: Not going to make a dark version because I personally won't use it. Anyone looking for a dark version check out @lavventura's awesome theme Reddit No Frills Dark +

https://userstyles.org/styles/133277/reddit-no-frills-dark
https://github.com/lavventura/reddit-no-frills-dark

**Comment by nicnic-cc** [comment]
I've made a dark version [fork](https://github.com/lavventura/reddit-no-frills-dark).
